// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxkyvelohybvcuidkuvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4a3l2ZWxvaHlidmN1aWRrdXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTMwMzIsImV4cCI6MjA2ODg2OTAzMn0.d0zjgJbwTG1u7jNS9rqAoBpPWu3xzKUKb31MBzkRFI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});